### ISSUE TITLE
How to create DNS service instance via Terraform to be the code example

### ISSUE THREAD

**Issue by miyamotoh** [ibm-cloud-docs/dns-svcs#4]
https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-terraform-setup-dns-svcs is supposed to be the getting-started with Terraform for the DNS services. Yet, the code snippet in Step 2 doesn't show how to create a service instance, and instead, it shows how to create a zone inside an (existing) instance. I think it should be replaced with how-to-create-a-service-instance example, as you can't do anything more interesting without having a service instance created first.

**Comment by moisesatwork** [comment]
@miyamotoh thank you for creating this issue 🙏
Currently the snippet in Step 2 that @miyamotoh is referring to, reads the following:
```
resource "ibm_dns_zone" "pdns-1-zone" {
 name = "my-dns-zone"
 instance_id = p-dns-instance-id
 description = "testdescription"
 label = "testlabel"
}
```
This is also shown in the screenshot below:
<img width="1126" alt="Screen Shot 2022-08-16 at 1 20 16 PM" src="https://user-images.githubusercontent.com/102981166/184950997-e8bad5d2-35e3-46a8-a36b-fe08ff107a72.png">

In order to create a private DNS zone, a private DNS instance needs to be created first. The snippet in step 2 does not include how to create a DNS instance. The private DNS instance resource block needs to be included in this block. The snippet must be updated to the following:

```
data "ibm_resource_group" "rg" {
  is_default = true
}

resource "ibm_resource_instance" "test-pdns-instance" {
  name              = "private-dns-instance-example"
  resource_group_id = data.ibm_resource_group.rg.id
  location          = "global"
  service           = "dns-svcs"
  plan              = "standard-dns"
}

resource "ibm_dns_zone" "pdns-1-zone" {
 name = "my-dns-zone"
 instance_id = ibm_resource_instance.test-pdns-cr-instance.guid
 description = "testdescription"
 label = "testlabel"
}
```
@sheltons thank you for reaching out and allowing me to provide an improvement to our documentation.

**Comment by sheltons** [comment]
Thanks, @moisesatwork. I'll get these changes pushed to staging, and then it'll get pushed to production!

**Comment by sheltons** [comment]
updated content is now in production. Closing.
